Repository haruki7049/hrtor, pull requests merged in 2023-12, with the labels that each got.

#52 created SUPPORT.md and SUPPORT_JP.md
  .github/SUPPORT.md
  .github/SUPPORT_JP.md
Labels: documentation

#48 created CONTRIBUTING.md and CONTRIBUTING_JP.md
  .github/CONTRIBUTING.md
  .github/CONTRIBUTING_JP.md
Labels: documentation

#63 Rewrite SUPPORT.md and SUPPORT_JP.md
  .github/SUPPORT.md
  .github/SUPPORT_JP.md
Labels: documentation

#60 Write CODE_OF_CONDUDT.md
  .github/CODE_OF_CONDUCT.md
  .github/CODE_OF_CONDUCT_JP.md
Labels: documentation

#61 Add hrtor's phonetic pronunciation
  README.md
Labels: documentation

#64 feat: created PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#69 fix: Rewrote src/bin/hrtor.rs
  src/bin/hrtor.rs
Labels: refactoring

#74 feat: hrtor echo and quit apis
  src/actions.rs
  src/actions/add.rs
  src/actions/write.rs
  src/bin/hrtor.rs
  src/file_loader.rs
  src/lib.rs
  src/user_script.rs
  src/user_script/lua.rs
  test_config.lua
Labels: enhancement

#75 Create hrtor.command.new()
  src/user_script/lua.rs
  test_config.lua
Labels: enhancement

#78 fix(user_script): rewrote user_script/lua.rs
  src/user_script/lua.rs
Labels: refactoring
